// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    if (!prop) return;   // a lookup that found nothing: skip rather than abort the build
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function exposureStops(fx) {
    // Exposure effect layout: 0001 Channels, 0002 "Master" group (no value) holding 0003 Exposure, 0004 Offset, 0005 Gamma.
    var cands = [fx.property("ADBE Exposure2-0003")];
    var grp = fx.property("ADBE Exposure2-0002");
    if (grp && grp.propertyValueType == PropertyValueType.NO_VALUE && grp.numProperties) cands.push(grp.property("ADBE Exposure2-0003"), grp.property(1));
    for (var i = 0; i < cands.length; i++) if (cands[i] && cands[i].propertyValueType == PropertyValueType.OneD) return cands[i];
    // last resort: the first scalar under any group in the effect
    for (var g = 1; g <= fx.numProperties; g++) {
        var q = fx.property(g);
        if (q.propertyType != PropertyType.PROPERTY) for (var j = 1; j <= q.numProperties; j++) if (q.property(j).propertyValueType == PropertyValueType.OneD) return q.property(j);
    }
    return null;
}
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "The Fifth Avenue Hotel";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 312 / FPS, FPS);
    comp.bgColor = [1.0000, 1.0000, 1.0000];

    var shots = [["B1 hold", 0], ["B2 lockup", 58], ["B3 lockup out", 101], ["B4 reveal", 130], ["B5 walk (Kling FA-1)", 173], ["B6 whip", 274], ["B6b white", 282], ["B7 return", 288], ["B8 loop", 306]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    comp.motionBlur = true;
    var parkItem  = importFootage("fa_park_couple_no_tortoise.png", null, folder);
    var leashItem = importFootage("leash.png", null, folder);
    var turtleItem = importFootage("turtle.png", null, folder);
    var lockItem  = importFootage("Asset 1@2x.png", null, folder);
    var walkItem  = importFootage("fa_1_t1.mp4", null, folder);
    var PS = 44.19;

    solid(comp, "White BG", [255, 255, 255], 1920, 1080, 0, 312);
    var park = null;
    if (parkItem) {
        park = addStill(comp, parkItem, "Park (background + couple)", 130, 282);
        place(park, null, [960, 540], 100);
        keys(opacity(park), [[130, 0], [173, 100]], false);
        keys(xf(park).property("ADBE Position"), [[274, [960, 540]], [282, [-960, 540]]], true);
        park.motionBlur = true;
        park.comment = "Whip: 2-frame ease-in, directional blur. Woman +12 px and man +15 px over the walk are on the PSD layers if they are used instead of this flattened plate.";
    }
    if (leashItem) {
        var le = addStill(comp, leashItem, "Leash", 165, 282);
        place(le, null, [923.6, 558.2], PS);
        keys(opacity(le), [[165, 0], [173, 100]], true);
        if (park) { le.parent = park; xf(le).property("ADBE Position").setValue([923.6, 558.2]); }
        le.motionBlur = true;
        le.comment = "Stretch the right end to follow the collar over the walk.";
    }
    if (walkItem) { var wk = addClip(comp, walkItem, "Kling walk — fa_1_t1.mp4 (optional; source f0-25 held over the beat)", 173, 274, 0, 404); wk.enabled = false;
        wk.comment = "Final: figures retimed to 1/6 with optical flow, background at normal speed (or a second pass on the background alone)."; }
    if (turtleItem) {
        var tt = addStill(comp, turtleItem, "Tortoise", 0, 312);
        place(tt, null, [1031, 413.5], PS);
        keys(xf(tt).property("ADBE Position"), [[130, [1031, 413.5]], [168, [1178, 748.5]], [288, [1178, 748.5]], [306, [1031, 413.5]]], true);
        tt.comment = "Optional +162 px in x over the walk (f173-274) then it stays for the whip. Specular sweep f10-50 as a masked light layer.";
    }
    if (lockItem) {
        var lk = addStill(comp, lockItem, "Lockup (textured gold)", 58, 118);
        place(lk, null, [960, 806], 16.66);
        linearWipe(lk, [[58, 100], [82, 0]], 90, 60);
        keys(opacity(lk), [[101, 100], [118, 0]], true);
        keys(xf(lk).property("ADBE Scale"), [[101, [16.66, 16.66]], [118, [17.16, 17.16]]], true);
    }
    log("Audio: nothing placed; clock ticks, harp glisses and a carriage pass are in Drive (5th ave hotel NYC/audio).");
    log("Loop: f311 must equal f0 (tortoise up-left on white).");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
