// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    if (!prop) return;   // a lookup that found nothing: skip rather than abort the build
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function exposureStops(fx) {
    // Exposure effect layout: 0001 Channels, 0002 "Master" group (no value) holding 0003 Exposure, 0004 Offset, 0005 Gamma.
    var cands = [fx.property("ADBE Exposure2-0003")];
    var grp = fx.property("ADBE Exposure2-0002");
    if (grp && grp.propertyValueType == PropertyValueType.NO_VALUE && grp.numProperties) cands.push(grp.property("ADBE Exposure2-0003"), grp.property(1));
    for (var i = 0; i < cands.length; i++) if (cands[i] && cands[i].propertyValueType == PropertyValueType.OneD) return cands[i];
    // last resort: the first scalar under any group in the effect
    for (var g = 1; g <= fx.numProperties; g++) {
        var q = fx.property(g);
        if (q.propertyType != PropertyType.PROPERTY) for (var j = 1; j <= q.numProperties; j++) if (q.property(j).propertyValueType == PropertyValueType.OneD) return q.property(j);
    }
    return null;
}
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "North Island";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 312 / FPS, FPS);
    comp.bgColor = [1.0000, 1.0000, 1.0000];

    var shots = [["S1 hold", 0], ["S2 flood", 53], ["S3 swim (Kling NI-2)", 96], ["S4a landfall", 168], ["S4b sand (Kling NI-3)", 197],
                 ["S5 return (Kling NI-4)", 226], ["S6a whiteout", 274], ["S6b loop", 298]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var whiteItem = importFootage("ni_lockup_white_1536x1024.png", null, folder);
    var waterItem = importFootage("ni_water_16x9_3641x2048.png", null, folder);
    var cutItem   = importFootage("ni_lockup_turtles_wordmark_alpha.png", "keyed from the white lock-up", folder);
    var swimItem  = importFootage("ni_2_t1.mp4", null, folder);
    var sandItem  = importFootage("ni_3_t1.mp4", null, folder);
    var backItem  = importFootage("ni_4_t1.mp4", null, folder);

    solid(comp, "White BG", [255, 255, 255], 1920, 1080, 0, 312);
    if (whiteItem) { var wl = addStill(comp, whiteItem, "Lock-up white", 0, 312); place(wl, null, [960, 540], 105.47); }
    if (waterItem) { var wa = addStill(comp, waterItem, "Water plate A", 53, 96); place(wa, null, [960, 540], 52.73); }
    var coverA = solid(comp, "Flood cover (wipe bottom→top)", [255, 255, 255], 1920, 1080, 53, 82);
    linearWipe(coverA, [[53, 0], [82, 100]], 180, 90);
    if (swimItem) addClip(comp, swimItem, "S3 swim — ni_2_t1.mp4", 96, 197, 0, 100);
    if (sandItem) { var sd = addClip(comp, sandItem, "S4 sand — ni_3_t1.mp4 (source f92 on f197)", 168, 226, 92, 100); keys(opacity(sd), [[168, 0], [197, 100]], true); }
    if (backItem) addClip(comp, backItem, "S5 return — ni_4_t1.mp4 (stretch 39.67 %)", 226, 274, 0, 39.67);
    if (waterItem) { var wb = addStill(comp, waterItem, "Water plate B", 258, 298); place(wb, null, [960, 540], 52.73); keys(opacity(wb), [[258, 0], [274, 100]], true); }
    var coverB = solid(comp, "Whiteout cover (wipe top→bottom)", [255, 255, 255], 1920, 1080, 274, 298);
    linearWipe(coverB, [[274, 100], [298, 0]], 180, 90);
    if (cutItem) {
        var c1 = addStill(comp, cutItem, "Turtles + wordmark cut-out (held over the flood)", 53, 96); place(c1, null, [960, 540], 105.47);
        var c2 = addStill(comp, cutItem, "Turtles + wordmark cut-out (held over the whiteout)", 274, 312); place(c2, null, [960, 540], 105.47);
        c2.comment = "The board holds the lock-up elements as one cut-out layer over both grounds so nothing pops; the plates' baked turtles sit 5-11 px off this.";
    }
    log("Loop: f311 must equal f0.");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
