// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    if (!prop) return;   // a lookup that found nothing: skip rather than abort the build
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function exposureStops(fx) {
    // Exposure effect layout: 0001 Channels, 0002 "Master" group (no value) holding 0003 Exposure, 0004 Offset, 0005 Gamma.
    var cands = [fx.property("ADBE Exposure2-0003")];
    var grp = fx.property("ADBE Exposure2-0002");
    if (grp && grp.propertyValueType == PropertyValueType.NO_VALUE && grp.numProperties) cands.push(grp.property("ADBE Exposure2-0003"), grp.property(1));
    for (var i = 0; i < cands.length; i++) if (cands[i] && cands[i].propertyValueType == PropertyValueType.OneD) return cands[i];
    // last resort: the first scalar under any group in the effect
    for (var g = 1; g <= fx.numProperties; g++) {
        var q = fx.property(g);
        if (q.propertyType != PropertyType.PROPERTY) for (var j = 1; j <= q.numProperties; j++) if (q.property(j).propertyValueType == PropertyValueType.OneD) return q.property(j);
    }
    return null;
}
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "Miavana";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 288 / FPS, FPS);
    comp.bgColor = [0.6157, 0.7843, 0.7176];

    var shots = [["B1 hold", 0], ["B2a wind-up", 58], ["B2b throw", 72], ["B2c catch", 92], ["B3 reveal", 101], ["B4 palms", 149], ["B5 return", 230], ["B6 hold / loop", 274]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var plateItem = importFootage("mi_palms_lemurs_comp_4988x2806.png", null, folder);
    var wmItem    = importFootage("mi_wordmark_fitted_alpha.png", "vector MIAVANA fitted 1730 px wide", folder);
    var isItem    = importFootage("miavana_0003_islandsanctuary.png", null, folder);
    var btItem    = importFootage("miavana_0004_bytimeandtide.png", null, folder);
    var seatItem  = importFootage("miavana_0000_left_lemur.png", null, folder);
    var hangItem  = importFootage("miavana_0001_right_lemur.png", null, folder);
    var mangoItem = importFootage("mi_mango_cutout_alpha.png", null, folder);
    var windItem  = importFootage("mi_2_t1.mp4", null, folder);
    var catchItem = importFootage("mi_3_t1.mp4", null, folder);
    var PS = 76.56;                                   // PSD px -> HD

    solid(comp, "Sage BG", [157, 200, 183], 1920, 1080, 0, 288);
    if (plateItem) {
        var pl = addStill(comp, plateItem, "Aerial with lemurs (drift R→L)", 101, 274);
        place(pl, null, [1018, 540], 40.8);
        keys(xf(pl).property("ADBE Position"), [[149, [1018, 540]], [230, [902, 540]]], true);
        keys(opacity(pl), [[101, 0], [149, 100], [230, 100], [274, 0]], false);
        pl.comment = "Colour-match the greens toward the sage so the change reads as focus, not a cut.";
    }
    var lockOp = [[0, 100], [101, 100], [125, 0], [230, 0], [274, 100]];
    if (wmItem) { var wm = addStill(comp, wmItem, "MIAVANA wordmark", 0, 288); place(wm, null, [976, 403.5], 100); keys(opacity(wm), lockOp, true); }
    if (isItem) { var is1 = addStill(comp, isItem, "ISLAND SANCTUARY", 0, 288); place(is1, null, [980.6, 677.7], PS); keys(opacity(is1), lockOp, true); }
    if (btItem) { var bt = addStill(comp, btItem, "BY TIME+TIDE", 0, 288); place(bt, null, [981.1, 994.2], PS); keys(opacity(bt), lockOp, true); }
    var lemOp = [[0, 100], [149, 100], [150, 0], [229, 0], [230, 100]];
    if (seatItem) { var se = addStill(comp, seatItem, "Seated lemur (PSD)", 0, 288); place(se, null, [120.5, 417.9], PS); keys(opacity(se), lemOp, false); }
    if (hangItem) { var ha = addStill(comp, hangItem, "Hanging lemur (PSD)", 0, 288); place(ha, null, [1749.7, 552.8], PS); keys(opacity(ha), lemOp, false);
        ha.comment = "Arm frees f58-70 for the throw (2-key puppet), or use the Kling wind-up clip."; }
    if (mangoItem) {
        var mg = addStill(comp, mangoItem, "Mango", 0, 288);
        var MS = 100 * 84 / 1709;                     // 84 px wide on screen
        place(mg, null, [1756, 645], MS);
        // throw: quadratic arc release (1750,651) -> apex (932,197) -> catch (207,344), sampled at 5 keys
        var P0 = [1750, 651], P1 = [932, 197], P2 = [207, 344], arc = [];
        for (var k = 0; k <= 4; k++) { var t = k / 4, u = 1 - t;
            var px = u * u * P0[0] + 2 * u * t * (2 * P1[0] - (P0[0] + P2[0]) / 2) + t * t * P2[0];
            var py = u * u * P0[1] + 2 * u * t * (2 * P1[1] - (P0[1] + P2[1]) / 2) + t * t * P2[1];
            arc.push([72 + 5 * k, [px, py]]); }
        var posKeys = [[0, [1756, 645]], [71, [1756, 645]]].concat(arc).concat([[101, [217, 340]], [230, [1756, 645]], [288, [1756, 645]]]);
        keys(xf(mg).property("ADBE Position"), posKeys, true);
        keys(xf(mg).property("ADBE Rotate Z"), [[72, 0], [82, 35], [92, 0]], true);
        keys(opacity(mg), [[0, 100], [101, 100], [102, 0], [229, 0], [230, 100]], false);
        mg.comment = "Second toss in beat 4 goes back left-to-right, apex 90 px lower, so the mango is home by f230.";
    }
    if (windItem) { var wi = addClip(comp, windItem, "Kling wind-up — mi_2_t1.mp4 (optional)", 58, 72, 0, 11.6); wi.enabled = false; }
    if (catchItem) { var ca = addClip(comp, catchItem, "Kling catch — mi_3_t1.mp4 (optional, source f44 on f72)", 72, 101, 44, 44.6); ca.enabled = false; }
    log("Loop: f287 must equal f0.");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
