// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "Giraffe Manor";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 384 / FPS, FPS);
    comp.bgColor = [1.0000, 1.0000, 0.9412];

    // ---- shot markers
    var shots = [["S1 hold", 0], ["S2 logo", 48], ["S3 enter", 86], ["S4 reveal", 154], ["S5 pull-back", 178], ["S6 turn (Kling GM-2 t3)", 216],
                 ["S7 windows (Kling GM-4)", 269], ["S8 payoff + mark", 322], ["S9 return", 351], ["S10 loop hold", 373]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);

    // ---- footage
    var heroItem  = importFootage("gm_hero_cutout_alpha.png", null, folder);
    var plateItem = importFootage("gm_manor_plate_no_giraffes.png", null, folder);
    var logoItem  = importFootage("giraffe_manor_wordmark.png", null, folder);
    var walkItem  = importFootage("giraffe_walking.mov", "Drive: Giraffe Manor/upscaled, 327 MB ProRes 4444 alpha, 30 fps", folder);
    var s6Item    = importFootage("gm_2_t3.mp4", null, folder);
    var s7Item    = importFootage("gm_4_t1.mp4", null, folder);
    var bedItem   = importFootage("birdsong01.wav", "Drive: Giraffe Manor/audio", folder);

    var HERO_ANCHOR = [489.5, 1505];           // bottom-centre of the giraffe in the 1024x1536 cut-out
    var HERO_SCALE = 53.8;                     // 800 px tall on the cream
    var PLATE_ANCHOR = [2140, 1490];           // pivot in plate px
    var PLATE_POS = [1497.5, 1047.7];
    var S0 = 70.31;                            // plate at 100 % of the frame height = 70.31 % of 2752x1536
    var Z = 2.65;

    // 1 cream background
    solid(comp, "Cream BG", [255, 255, 240], 1920, 1080, 0, 384);

    // 2 hero on cream (the loop frame)
    if (heroItem) {
        var hero = addStill(comp, heroItem, "Hero on cream", 0, 384);
        place(hero, HERO_ANCHOR, [760, 880], HERO_SCALE);
    }

    // 3 walker on cream: enters from the right f86-154 and stops beside the hero
    if (walkItem) {
        var walker = addClip(comp, walkItem, "Walker on cream (giraffe_walking.mov)", 86, 154, 0, 100);
        place(walker, null, [1945, 621], 50);
        keys(xf(walker).property("ADBE Position"), [[86, [1945, 621]], [154, [1065, 621]]], true);
        walker.comment = "Colour-match to the hero: the walker is warmer and darker (per-channel levels, gain <= 1.35).";
    }

    // 4 logo small under the hooves
    if (logoItem) {
        var logo = addStill(comp, logoItem, "Wordmark small", 48, 178);
        place(logo, null, [760, 969], 16.2);
        keys(xf(logo).property("ADBE Scale"), [[48, [15.5, 15.5]], [67, [16.2, 16.2]]], true);
        keys(opacity(logo), [[48, 0], [67, 100], [120, 100], [154, 35], [178, 0]], true);
    }

    // 5 manor plate: dissolves in large and soft, rack focus, pull-back to 100 %
    var plate = null;
    if (plateItem) {
        plate = addStill(comp, plateItem, "Manor plate", 154, 222);
        place(plate, PLATE_ANCHOR, PLATE_POS, S0 * Z);
        keys(xf(plate).property("ADBE Scale"), [[154, [S0 * Z, S0 * Z]], [188, [S0 * Z, S0 * Z]], [216, [S0, S0]]], true);
        keys(opacity(plate), [[154, 0], [178, 100]], true);
        var blur = effect(plate, "ADBE Gaussian Blur 2", "Rack focus");
        keys(blur.property("ADBE Gaussian Blur 2-0001"), [[154, 20], [178, 20], [188, 0]], true);
    }

    // 6 hero on the plate (parented), feet at plate px (1744, 1400), 429 plate px tall
    if (heroItem && plate) {
        var heroP = addStill(comp, heroItem, "Hero on plate", 154, 222);
        heroP.parent = plate;
        place(heroP, HERO_ANCHOR, [1744, 1400], 28.85);
        keys(opacity(heroP), [[154, 0], [178, 100]], true);
    }

    // 7 walker frozen on the plate (parented), source frame 85, feet at plate px (2050, 1400)
    if (walkItem && plate) {
        var walkP = addClip(comp, walkItem, "Walker on plate (frozen f85)", 154, 222, 0, 100);
        freeze(walkP, 85);
        walkP.parent = plate;
        place(walkP, null, [1954, 1239], 27.8);
        keys(opacity(walkP), [[154, 0], [178, 100]], true);
        walkP.comment = "Placement approximates the animatic: feet centre (2050, 1400) plate px, 429 plate px tall. Nudge to taste.";
    }

    // 8 shot 6: the turn (Kling GM-2 take 3), 121 source frames into 63
    if (s6Item) {
        var s6 = addClip(comp, s6Item, "S6 turn — gm_2_t3.mp4 (stretch 52.07 %)", 216, 269, 0, 52.07);
        keys(opacity(s6), [[216, 0], [222, 100]], true);
        s6.comment = "No in-place turn in the clip: the giraffes travel to the steps and end rear-facing. Roto/retime candidate.";
    }

    // 9 shots 7-9: heads into the windows (Kling GM-4), plays on under the mark, dissolves out to the hero
    if (s7Item) {
        var s7 = addClip(comp, s7Item, "S7-9 windows — gm_4_t1.mp4", 269, 373, 0, 100);
        keys(opacity(s7), [[351, 100], [373, 0]], true);
    }

    // 10-11 end card + mark, bottom-right
    var card = solid(comp, "End card", [255, 255, 240], 444, 115, 322, 373);
    place(card, null, [1638, 962.5], 100);
    keys(opacity(card), [[322, 0], [334, 88], [351, 88], [373, 0]], true);
    card.comment = "Round the corners 14 px (mask) if wanted.";
    if (logoItem) {
        var mark = addStill(comp, logoItem, "End mark", 322, 373);
        place(mark, null, [1638, 962.5], 10.12);
        keys(opacity(mark), [[322, 0], [334, 100], [351, 100], [373, 0]], true);
    }

    // 12 audio bed
    if (bedItem) {
        var bed = comp.layers.add(bedItem); bed.name = "birdsong01.wav (-14 dB)";
        bed.startTime = 0; span(bed, 0, 384);
        keys(audioLevels(bed), [[0, [-96, -96]], [12, [-14, -14]], [372, [-14, -14]], [384, [-96, -96]]], false);
    }
    log("Loop: f383 must equal f0 (hero on cream, nothing else).");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
