// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "Passalacqua";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 360 / FPS, FPS);
    comp.bgColor = [1.0000, 1.0000, 1.0000];

    var shots = [["B1 crest", 0], ["B2 wordmark", 48], ["B3 fill", 86], ["B4 alive (Kling PA-2)", 120], ["B5 lake (Kling PA-3)", 158],
                 ["B6 leap (Kling PA-4)", 197], ["B7 end card", 293], ["B8 settle", 312], ["B9 flatten", 336], ["B10 loop", 355]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var fishArt = importFootage("pa_crest_fish_lineart.png", null, folder);
    var waveArt = importFootage("pa_crest_wave_rule.png", null, folder);
    var typeArt = importFootage("pa_crest_type.png", null, folder);
    var waveW   = importFootage("pa_crest_wave_rule_white.png", null, folder);
    var typeW   = importFootage("pa_crest_type_white.png", null, folder);
    var gold = [importFootage("pa_gold_fish_L.png", null, folder), importFootage("pa_gold_fish_C.png", null, folder), importFootage("pa_gold_fish_R.png", null, folder)];
    var aliveItem = importFootage("pa_2_t1.mp4", null, folder);
    var dropItem  = importFootage("pa_3_t1.mp4", null, folder);
    var leapItem  = importFootage("pa_4_t1.mp4", null, folder);
    var lastItem  = importFootage("pa_4_last_frame.png", null, folder);
    var CS = 39.32;                                   // crest scale
    var GS = 28.36;                                   // gold fish scale (registered on the line art)

    solid(comp, "White BG", [255, 255, 255], 1920, 1080, 0, 360);
    if (aliveItem) { var al = addClip(comp, aliveItem, "B4 alive — pa_2_t1.mp4", 120, 158, 0, 100); keys(opacity(al), [[120, 0], [126, 100]], true); }
    if (dropItem)  { var dr = addClip(comp, dropItem, "B5 drop — pa_3_t1.mp4 (stretch 32.2 %)", 158, 197, 0, 32.2); keys(opacity(dr), [[158, 0], [170, 100]], true); }
    if (leapItem)  addClip(comp, leapItem, "B6 leap — pa_4_t1.mp4 (stretch 79.3 %)", 197, 293, 0, 79.3);
    if (lastItem)  { var hl = addStill(comp, lastItem, "B7 held lake (last frame of the leap)", 293, 336); hl.comment = "Desaturate 50 % here (Hue/Saturation); rings spread from (960, 555) f293-312 as a shape layer."; }
    var dark = solid(comp, "End-card darken", [0, 10, 25], 1920, 1080, 293, 336); keys(opacity(dark), [[293, 0], [305, 59]], true);
    var wr = solid(comp, "White return", [255, 255, 255], 1920, 1080, 312, 360); keys(opacity(wr), [[312, 0], [336, 100]], true);
    if (waveArt) { var wv = addStill(comp, waveArt, "Wave rule, line art", 0, 360); place(wv, null, [957.4, 554.5], CS); }
    if (fishArt) { var fa = addStill(comp, fishArt, "Fish, line art", 0, 360); place(fa, null, [957.4, 343.6], CS); }
    var homeX = [819.5, 958.5, 1100.5], names = ["L", "C", "R"], rot = [-6, 3, -4], dy = [90, 60, 110];
    for (var g = 0; g < 3; g++) {
        if (!gold[g]) continue;
        var gf = addStill(comp, gold[g], "Gold fish " + names[g], 100, 355);
        place(gf, null, [homeX[g], 343.5], GS);
        keys(opacity(gf), [[100, 100], [126, 100], [132, 0], [311, 0], [312, 100]], false);
        // B3 fill from the tail up (completion 100 -> 0 reveals bottom-up at angle 0), B9 drain head-down (0 -> 100)
        var fx = linearWipe(gf, [[100 + 3 * g, 100], [116 + 3 * g, 0], [335, 0], [336 + 3 * (2 - g), 0], [348 + 3 * (2 - g), 100]], 0, 12);
        // B8 settle: rise from below at 112 %, small rotation, to the registered position
        keys(xf(gf).property("ADBE Position"), [[312, [homeX[g], 343.5 + dy[g]]], [336, [homeX[g], 343.5]]], true);
        keys(xf(gf).property("ADBE Rotate Z"), [[312, rot[g]], [336, 0]], true);
        keys(xf(gf).property("ADBE Scale"), [[312, [GS * 1.12, GS * 1.12]], [336, [GS, GS]]], true);
    }
    if (typeArt) { var ty = addStill(comp, typeArt, "Type, black", 48, 355); place(ty, null, [957.4, 798.7], CS);
        keys(opacity(ty), [[48, 0], [67, 100], [86, 100], [98, 0], [312, 0], [336, 100], [343, 100], [355, 0]], true); }
    if (typeW) { var tw = addStill(comp, typeW, "Type, white (end card)", 293, 336); place(tw, null, [957.4, 798.7], CS); keys(opacity(tw), [[293, 0], [305, 100], [312, 100], [336, 0]], true); }
    if (waveW) { var ww = addStill(comp, waveW, "Wave rule, white (end card)", 293, 336); place(ww, null, [957.4, 554.5], CS); keys(opacity(ww), [[293, 0], [305, 100], [312, 100], [336, 0]], true); }
    log("Loop: f359 must equal f0 (line-art fish + wave rule on white).");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
