// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    for (var k = tr.numKeys; k >= 1; k--) tr.removeKey(k);
    tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t);
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "Versailles";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 374 / FPS, FPS);
    comp.bgColor = [0.0000, 0.0000, 0.0000];

    var shots = [["S1 open", 0], ["S2 reveal", 53], ["S3 wordmark", 106], ["S4 morph", 149], ["S5 still", 211], ["S6 drop", 235], ["S7 served", 254], ["S8 return", 326]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var salonItem = importFootage("ve_1_t1.png", null, folder);
    var markItem  = importFootage("ve_wordmark_gold_alpha.png", null, folder);
    var gUpItem   = importFootage("ve_guillotine_up_alpha.png", null, folder);
    var gDnItem   = importFootage("ve_guillotine_down_alpha.png", null, folder);
    var cakeItem  = importFootage("ve_cake_table_alpha.png", null, folder);
    var platItem  = importFootage("ve_plated_alpha.png", null, folder);
    var chanItem  = importFootage("ve_chandelier_alpha.png", null, folder);

    solid(comp, "Black BG", [0, 0, 0], 1920, 1080, 0, 374);
    if (salonItem) {
        var sa = addStill(comp, salonItem, "Clean salon", 53, 350);
        place(sa, null, [960, 540], 114.8);
        // radial reveal: an elliptical mask in layer px (layer is 1672x941), expansion keyed open then shut
        var m = ellipseMask(sa, 836, 540, 174, 139, 260);
        keys(m.property("ADBE Mask Offset"), [[53, 0], [86, 1300], [326, 1300], [350, -200]], true);
        var ex = effect(sa, "ADBE Exposure2", "Grade (stops)");
        keys(ex.property("ADBE Exposure2-0002"), [[149, 0], [211, -1.5], [254, -1.5], [270, -0.5], [350, -0.5], [370, 0]], true);
        sa.comment = "If the Exposure effect's property index is off, the keyed property is Master Exposure: 0 / -1.5 / -0.5 / 0 stops.";
    }
    if (markItem) { var mk = addStill(comp, markItem, "Wordmark (gold-cream)", 106, 223); place(mk, null, [960, 997], 37.5); keys(opacity(mk), [[106, 0], [123, 100], [211, 100], [223, 0]], true); }
    if (gUpItem) { var gu = addStill(comp, gUpItem, "Guillotine, blade up", 149, 370); place(gu, [388, 1040], [960, 1050], 100); keys(opacity(gu), [[149, 0], [200, 100], [350, 100], [370, 0]], true);
        gu.comment = "Morph target: crystals -> uprights f149-180, boss -> blade f170-200, rope draws on f195-211."; }
    if (gDnItem) { var gd = addStill(comp, gDnItem, "Guillotine, blade down (impact stand-in)", 238, 362); place(gd, [388, 1040], [960, 1050], 100); keys(opacity(gd), [[238, 0], [246, 100], [338, 100], [362, 0]], true);
        gd.comment = "Final: cut the blade from this still and move it down over f238-246."; }
    if (cakeItem) { var ck = addStill(comp, cakeItem, "Cake on table", 0, 374); place(ck, [231.5, 620], [960, 1042], 100); keys(opacity(ck), [[254, 100], [268, 0], [338, 0], [362, 100]], true); }
    if (platItem) { var pt = addStill(comp, platItem, "Plated slices", 254, 362); place(pt, [350, 700], [960, 1072], 100); keys(opacity(pt), [[254, 0], [268, 100], [338, 100], [362, 0]], true);
        pt.comment = "Final: separate slice cut-outs slide out over 0.6 s and back at 2x on the return."; }
    if (chanItem) { var ch = addStill(comp, chanItem, "Chandelier", 0, 374); place(ch, [112, 0], [960, 8], 100); keys(opacity(ch), [[149, 100], [200, 0], [350, 0], [370, 100]], true); }
    var gr = adjustment(comp, "Grade: elements (stops)", 149, 370);
    var ex2 = effect(gr, "ADBE Exposure2", "Grade (stops)");
    keys(ex2.property("ADBE Exposure2-0002"), [[149, 0], [211, -1.5], [254, -1.5], [270, -0.5], [350, -0.5], [370, 0]], true);
    var fl = solid(comp, "Flash", [255, 255, 255], 1920, 1080, 246, 249); opacity(fl).setValue(35);
    fl.comment = "Kick the whole comp (+4, -3) px at f246 settling by f254, 1 px jitter f235-238: a null parent on the element layers.";
    log("Loop: f373 must equal f0 (cake + chandelier on black, grade 0).");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
