// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;     // AE adds two keys; removing them all would hide the property again
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    if (tr.numKeys == 0) { tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t); }
    for (var k = 1; k <= tr.numKeys; k++) {
        tr.setValueAtKey(k, t);
        try { tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD); } catch (e) {}
    }
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "Necker Island";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 372 / FPS, FPS);
    comp.bgColor = [1.0000, 1.0000, 1.0000];

    var shots = [["S1 hold", 0], ["S2 takeoff (Kling NE-1)", 58], ["S3 pull-back", 110], ["S4 kite (Kling NE-3)", 178], ["S5 tennis", 245], ["S6 whiteout", 312], ["S7 landing (Kling NE-5)", 336]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var birdItem = importFootage("flamingo.png", null, folder);
    var aerItem  = importFootage("ne_aerial_16x9_3840x2160.png", null, folder);
    var tkItem   = importFootage("ne_1_t1.mp4", null, folder);
    var kiteItem = importFootage("ne_3_t1.mp4", null, folder);
    var taItem   = importFootage("ne_4a_t1.png", null, folder);
    var tbItem   = importFootage("ne_4b_t1.png", null, folder);
    var ldItem   = importFootage("ne_5_t1.mp4", null, folder);
    var BIRD_ANCHOR = [457.5, 1666];

    solid(comp, "White BG", [255, 255, 255], 1920, 1080, 0, 372);
    if (birdItem) { var b1 = addStill(comp, birdItem, "Flamingo still", 0, 372); place(b1, BIRD_ANCHOR, [920, 940], 46.64);
        keys(opacity(b1), [[0, 100], [62, 100], [63, 0], [365, 0], [366, 100]], false); }
    if (tkItem) { var tk = addClip(comp, tkItem, "S2 takeoff — ne_1_t1.mp4 (stretch 43 %)", 58, 110, 0, 43); keys(opacity(tk), [[58, 0], [62, 100]], true);
        tk.comment = "Background drifts light grey: key or lift to white."; }
    if (aerItem) { var a1 = addStill(comp, aerItem, "Aerial, pull-back", 110, 178); place(a1, null, [960, 540], 110); keys(xf(a1).property("ADBE Scale"), [[110, [110, 110]], [178, [50, 50]]], true); }
    var ramp = solid(comp, "White ramp (pull-back)", [255, 255, 255], 1920, 1080, 110, 140); keys(opacity(ramp), [[110, 85], [140, 0]], true);
    if (birdItem) { var bs = addStill(comp, birdItem, "Flamingo small (stand-in flier)", 110, 178); place(bs, BIRD_ANCHOR, [1313, 461], 5.16);
        keys(xf(bs).property("ADBE Position"), [[110, [1313, 461]], [178, [1623, 381]]], true); bs.comment = "Replace with a flight-pose crop (necker_flamingos_08.jpg in Drive) or a Kling flier."; }
    if (kiteItem) addClip(comp, kiteItem, "S4 kite — ne_3_t1.mp4 (stretch 55.4 %)", 178, 245, 0, 55.37);
    if (taItem) { var ta = addStill(comp, taItem, "Tennis A", 245, 312); place(ta, null, [960, 540], 71.43); keys(xf(ta).property("ADBE Scale"), [[245, [71.43, 71.43]], [312, [82.14, 82.14]]], true); }
    if (tbItem) { var tb = addStill(comp, tbItem, "Tennis B", 245, 312); place(tb, null, [960, 540], 71.43); keys(xf(tb).property("ADBE Scale"), [[245, [71.43, 71.43]], [312, [82.14, 82.14]]], true);
        keys(opacity(tb), [[245, 0], [259, 0], [263, 100], [278, 100], [282, 0], [298, 0], [302, 100]], true); tb.comment = "Ball: AE shape on 14-frame arcs between the rackets, hits at 10.8 / 11.6 / 12.4 s."; }
    if (aerItem) { var a2 = addStill(comp, aerItem, "Aerial, whiteout", 312, 336); place(a2, null, [960, 540], 50); keys(xf(a2).property("ADBE Scale"), [[312, [50, 50]], [336, [27.5, 27.5]]], true); }
    var wo = solid(comp, "White ramp (whiteout)", [255, 255, 255], 1920, 1080, 312, 336); keys(opacity(wo), [[312, 0], [336, 100]], true);
    if (birdItem) { var bb = addStill(comp, birdItem, "Flamingo small (banking back)", 312, 336); place(bb, BIRD_ANCHOR, [1623, 381], 5.16);
        keys(xf(bb).property("ADBE Position"), [[312, [1623, 381]], [336, [1463, 461]]], true); }
    if (ldItem) { var ld = addClip(comp, ldItem, "S7 landing — ne_5_t1.mp4 (source f20 on f336, stretch 45 %)", 336, 372, 20, 45); keys(opacity(ld), [[366, 100], [371, 0]], true); }
    log("Virgin script mark, small, lower right, f318-336: not in the assets (client file).");
    log("Loop: f371 must equal f0.");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
