// Generated by tools/build_ae_jsx.py — do not edit by hand; edit the spec and regenerate.
// ExtendScript (ES3). Run from After Effects: File > Scripts > Run Script File, with this file next to assets/.
var FPS = 24;
function T(f) { return f / FPS; }
var __scriptFile = new File($.fileName);
var __base = __scriptFile.parent;
var __log = [];
function log(s) { __log.push(s); }

function assetFile(rel, hint) {
    var f = new File(__base.fsName + "/assets/" + rel);
    if (f.exists) return f;
    var g = File.openDialog("Locate " + rel + (hint ? "  (" + hint + ")" : "") + " — Cancel to skip this layer");
    if (g && g.exists) return g;
    log("SKIPPED (not found): " + rel);
    return null;
}
function importFootage(rel, hint, folder) {
    var f = assetFile(rel, hint);
    if (!f) return null;
    var io = new ImportOptions(f);
    try { if (io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE; } catch (e) {}
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
}
function xf(layer) { return layer.property("ADBE Transform Group"); }
function setEase(prop) {
    var n = prop.numKeys;
    for (var k = 1; k <= n; k++) {
        try {
            var dims = 1;
            if (prop.propertyValueType == PropertyValueType.TwoD || prop.propertyValueType == PropertyValueType.TwoD_SPATIAL) dims = 2;
            if (prop.propertyValueType == PropertyValueType.ThreeD || prop.propertyValueType == PropertyValueType.ThreeD_SPATIAL) dims = 3;
            var ea = [];
            for (var d = 0; d < dims; d++) ea.push(new KeyframeEase(0, 33));
            prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
            prop.setTemporalEaseAtKey(k, ea, ea);
        } catch (e) {}
    }
}
function keys(prop, arr, ease) {   // arr = [[frame, value], ...]
    for (var i = 0; i < arr.length; i++) prop.setValueAtTime(T(arr[i][0]), arr[i][1]);
    if (ease) setEase(prop);
}
function span(layer, fin, fout) { layer.inPoint = T(fin); layer.outPoint = T(fout); }
function place(layer, anchor, pos, scalePct) {
    if (anchor) xf(layer).property("ADBE Anchor Point").setValue(anchor);
    if (pos) xf(layer).property("ADBE Position").setValue(pos);
    if (scalePct !== null && scalePct !== undefined) xf(layer).property("ADBE Scale").setValue([scalePct, scalePct]);
}
function addStill(comp, item, name, fin, fout) {
    var L = comp.layers.add(item); L.name = name;
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function addClip(comp, item, name, fin, fout, srcFrame, stretchPct) {
    // source frame `srcFrame` lands on comp frame `fin`; stretchPct 100 = normal speed
    var L = comp.layers.add(item); L.name = name;
    if (stretchPct && stretchPct != 100) L.stretch = stretchPct;
    var st = (stretchPct ? stretchPct : 100) / 100;
    L.startTime = T(fin) - T(srcFrame || 0) * st;
    span(L, fin, fout);
    return L;
}
function freeze(layer, srcFrame) {   // hold one source frame for the whole layer span
    layer.timeRemapEnabled = true;
    var tr = layer.property("ADBE Time Remapping");
    var t = T(srcFrame);
    for (var k = tr.numKeys; k >= 1; k--) tr.removeKey(k);
    tr.setValueAtTime(layer.inPoint, t); tr.setValueAtTime(layer.outPoint, t);
}
function solid(comp, name, rgb, w, h, fin, fout) {
    var L = comp.layers.addSolid([rgb[0] / 255, rgb[1] / 255, rgb[2] / 255], name, w, h, 1.0, comp.duration);
    L.startTime = T(fin); span(L, fin, fout);
    return L;
}
function opacity(layer) { return xf(layer).property("ADBE Opacity"); }
function effect(layer, matchName, displayName) {
    var fx = layer.property("ADBE Effect Parade").addProperty(matchName);
    if (displayName) try { fx.name = displayName; } catch (e) {}
    return fx;
}
function marker(comp, f, text) { try { comp.markerProperty.setValueAtTime(T(f), new MarkerValue(text)); } catch (e) {} }
function audioLevels(layer) { return layer.property("ADBE Audio Group").property("ADBE Audio Levels"); }
function linearWipe(layer, completionKeys, angleDeg, feather) {
    var fx = effect(layer, "ADBE Linear Wipe", "Wipe");
    keys(fx.property("ADBE Linear Wipe-0001"), completionKeys, true);
    fx.property("ADBE Linear Wipe-0002").setValue(angleDeg);
    fx.property("ADBE Linear Wipe-0003").setValue(feather);
    layer.comment = (layer.comment ? layer.comment + " " : "") + "If the wipe runs the wrong way, add 180 to Wipe Angle.";
    return fx;
}
function ellipseMask(layer, cx, cy, rx, ry, feather) {
    // an elliptical mask in layer space; 4 vertices with bezier tangents (kappa 0.5523)
    var k = 0.5523;
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape();
    sh.vertices = [[cx, cy - ry], [cx + rx, cy], [cx, cy + ry], [cx - rx, cy]];
    sh.inTangents = [[-rx * k, 0], [0, -ry * k], [rx * k, 0], [0, ry * k]];
    sh.outTangents = [[rx * k, 0], [0, ry * k], [-rx * k, 0], [0, -ry * k]];
    sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function polyMask(layer, pts, feather) {
    var m = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var sh = new Shape(); sh.vertices = pts; sh.closed = true;
    m.property("ADBE Mask Shape").setValue(sh);
    if (feather) m.property("ADBE Mask Feather").setValue([feather, feather]);
    return m;
}
function adjustment(comp, name, fin, fout) {
    var L = solid(comp, name, [255, 255, 255], comp.width, comp.height, fin, fout);
    L.adjustmentLayer = true;
    return L;
}

(function () {
    var COMP_NAME = "22 Club";
    app.beginUndoGroup("Build " + COMP_NAME);
    var proj = app.project || app.newProject();
    var folder = proj.items.addFolder(COMP_NAME + " assets");
    var comp = proj.items.addComp(COMP_NAME, 1920, 1080, 1.0, 290 / FPS, FPS);
    comp.bgColor = [0.0000, 0.0000, 0.0000];

    var shots = [["B1 hold (beat 1)", 0], ["B2 flip (beat 5)", 46], ["B3 decks (beat 10)", 105], ["B4 spotlight (beat 14)", 151], ["B5 flip back (beat 18)", 197], ["B6 return (beat 23)", 255], ["cut to black (beat 25)", 279]];
    for (var i = 0; i < shots.length; i++) marker(comp, shots[i][1], shots[i][0]);
    var lItem = importFootage("cl_mark_2L.png", null, folder);
    var rItem = importFootage("cl_mark_2R.png", null, folder);
    var cItem = importFootage("cl_mark_club.png", null, folder);
    var platItem = importFootage("cl_1_t2.png", "platter + tonearm still", folder);
    var vinItem  = importFootage("cl_2_t1.png", "vinyl top-down still", folder);
    var bedItem  = importFootage("club22_rhythm_124bpm.wav", "placeholder bed", folder);
    var HINGE = 642, LX = 775, RX = 1145;

    solid(comp, "Black BG", [0, 0, 0], 1920, 1080, 0, 290);
    // spotlight: cone + pool as white solids with masks, keyed opacity (geometry at the f180 state)
    var cone = solid(comp, "Spotlight cone", [255, 240, 210], 1920, 1080, 151, 255);
    polyMask(cone, [[-80, -160], [1425, 560], [495, 700]], 6);
    keys(opacity(cone), [[151, 0], [158, 22], [197, 22], [255, 0]], true);
    cone.comment = "Sweep: the pool grows from the left deck (f158) to both (f180). Add noise-driven dust. cl_3_t1.png is the lighting reference.";
    var pool = solid(comp, "Spotlight pool", [255, 240, 210], 1920, 1080, 151, 255);
    ellipseMask(pool, 960, 600, 465, 135, 40);
    keys(opacity(pool), [[151, 0], [158, 35], [197, 35], [255, 0]], true);
    var deckOp = [[105, 0], [129, 100], [197, 100], [216, 0]];
    var cxs = [LX, RX];
    for (var d = 0; d < 2; d++) {
        if (platItem) { var pl = addStill(comp, platItem, "Platter " + (d ? "R" : "L"), 105, 216); place(pl, [940, 543], [cxs[d], 562], 19); pl.blendingMode = BlendingMode.SCREEN; keys(opacity(pl), deckOp, true);
            pl.comment = "Screen over black; the still's platter content box is x 93-1787, y 191-895. Scale to a 320 px platter."; }
        if (vinItem) { var vn = addStill(comp, vinItem, "Vinyl " + (d ? "R" : "L"), 105, 216); place(vn, [787.5, 763.5], [cxs[d], 562], 21); xf(vn).property("ADBE Scale").setValue([21, 10.5]);
            vn.blendingMode = BlendingMode.SCREEN; keys(opacity(vn), deckOp, true);
            keys(xf(vn).property("ADBE Rotate Z"), [[130, 0], [216, 720]], false); vn.comment = "33 1/3 rpm = 43 frames per rev from f130; squashed to the 30-degree view. One flash per rev."; }
    }
    // the digits as 3D layers hinged on their lowest ink row, seen from a camera 30 degrees above
    var cam = comp.layers.addCamera("Camera 30 up", [960, HINGE]);
    cam.property("ADBE Transform Group").property("ADBE Position").setValue([960, HINGE - 1333, -2309]);
    cam.property("ADBE Transform Group").property("ADBE Anchor Point").setValue([960, HINGE, 0]);
    function digit(item, name, homeX, drift, f0, f1) {
        var L = addStill(comp, item, name, 0, 279);
        L.threeDLayer = true;
        xf(L).property("ADBE Anchor Point").setValue([74.5, 362, 0]);
        xf(L).property("ADBE Position").setValue([homeX, HINGE, 0]);
        keys(xf(L).property("ADBE Rotate X"), [[f0, 0], [f1, 90], [216, 90], [235, 0]], true);
        keys(xf(L).property("ADBE Position"), [[f0, [homeX, HINGE, 0]], [f1, [homeX + drift, HINGE, 0]], [216, [homeX + drift, HINGE, 0]], [235, [homeX, HINGE, 0]]], true);
        keys(opacity(L), [[105, 100], [129, 0], [197, 0], [216, 100]], false);
        L.comment = "Rotate about an axis 2 px behind the face; small overshoot and settle on both flips.";
        return L;
    }
    if (lItem) digit(lItem, "Digit 2 L", 882.5, -107, 46, 65);
    if (rItem) digit(rItem, "Digit 2 R", 1034.5, 110, 54, 73);
    if (cItem) { var cl = addStill(comp, cItem, "club script", 0, 279); place(cl, null, [960.5, 728.5], 100); keys(opacity(cl), [[151, 100], [158, 65], [197, 65], [255, 100]], true); }
    if (bedItem) { var bed = comp.layers.add(bedItem); bed.name = "club22_rhythm_124bpm.wav (placeholder, -6 dB)"; bed.startTime = 0; span(bed, 0, 290); audioLevels(bed).setValue([-6, -6]); }
    log("Seamless-loop deliverable: trim at f279 (f278 = f0). Full cut ends on black.");

    try { app.project.timeDisplayType = TimeDisplayType.FRAMES; } catch (e) {}
    comp.openInViewer();
    app.endUndoGroup();
    var msg = COMP_NAME + " built: " + comp.numLayers + " layers, " + Math.round(comp.duration * FPS) + " frames at " + FPS + " fps.";
    if (__log.length) msg += "\n\nNotes:\n" + __log.join("\n");
    alert(msg);
})();
